apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalio
  labels: {{ include "avalio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "avalio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "avalio.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["avalio", "--config", "./config.toml"]
          volumeMounts:
            - name: config-volume
              mountPath: /app/
      volumes:
        - name: config-volume
          configMap:
            name: avalio-config
