
replicaCount: 1

image:
  repository: "avalio"
  pullPolicy: IfNotPresent
  tag: "latest"

config: | 
  [[monitors.http]]
  name = "example"
  expected_status_code = 200
  url = "https://example.com"
  delay_seconds = 300

  [[senders.telegram]]
  token = "..."
  chat_id = "111111"
